build:
  image: docker.stackdot.com/lib/node:5.11.0
  pull: true
  auth_config:
    username: drone
    password: $$DRONE_REGISTRY_PASS
    email: drone@tstllc.net
  commands:
    - npm update
    - node_modules/gulp/bin/gulp.js

publish:
  docker:
    repo: stackdot/swagger-ui
    tag:
      - '$${BRANCH/master/latest}'
      - '$$BRANCH.$$BUILD_NUMBER'
    registry: docker.stackdot.com
    username: $$DRONE_REGISTRY_USER
    password: $$DRONE_REGISTRY_PASS
    email: drone@stackdot.com
    storage_driver: overlay

deploy:
  rancher:
    url: $$RANCHER_URL
    access_key: $$RANCHER_KEY
    secret_key: $$RANCHER_SECRET
    service: stackdot/swagger-ui
    docker_image: docker.stackdot.com/stackdot/swagger-ui:$$BRANCH.$$BUILD_NUMBER
    confirm: true
    timeout: 300
    when:
      branch: master
    
cache:
  mount:
    - node_modules