
pipeline:
  compile:
    image: docker.stackdot.com/lib/node:6.3.1
    commands:
      - npm update
      - npm run build

  docker:
    image: plugins/docker
    repo: docker.stackdot.com/stackdot/docs
    tag:
      - '${DRONE_BRANCH/master/latest}'
      - '${DRONE_BRANCH}.build-${DRONE_BUILD_NUMBER}'
    storage_driver: overlay
    when:
      branch: master

  # deploy:
  #   image: vallard/drone-kube
  #   template: kube.yml
  #   namespace: gathir
  #   when:
  #     branch: master
